Improve error handling

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -58,10 +58,14 @@ runs:
     - name: Check delta
       shell: bash
       run: |
-        cat snyk.json | snyk-delta && true
-        if [ $? -ne 0 ]; then
-            echo "::error ::New issues were found! Refer to the Snyk report found in the Artifacts section of the Job Summary."
-            return 1
+        set +e
+        cat snyk.json | snyk-delta
+        exit_code=$?
+        if [ $exit_code -ne 0 ]; then
+            if [ $exit_code -eq 1 ]; then
+              echo "::error ::New issues were found! Refer to the Snyk report found in the Artifacts section of the Job Summary."
+            fi
+            exit $exit_code
         fi
       env:
         SNYK_TOKEN: ${{ inputs.snyk-token }}
